services:
  djangoapp:
    container_name: djangoapp
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./djangoapp:/djangoapp
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - psql

  psql:
    container_name: psql
    image: postgres:14.12-bookworm
    ports:
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql/data
    env_file:
      - ./dotenv_files/.env