# Generated by Django 5.0.6 on 2024-07-01 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estrela',
            fields=[
                ('id_estrela', models.CharField(max_length=31, primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=31, null=True)),
                ('classificacao', models.CharField(blank=True, max_length=31, null=True)),
                ('massa', models.FloatField(blank=True, null=True)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
            ],
            options={
                'db_table': 'estrela',
                'managed': True,
                'unique_together': {('x', 'y', 'z')},
            },
        ),
        migrations.CreateModel(
            name='Federacao',
            fields=[
                ('nome', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('data_fund', models.DateField()),
            ],
            options={
                'db_table': 'federacao',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Planeta',
            fields=[
                ('id_astro', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('massa', models.FloatField(blank=True, null=True)),
                ('raio', models.FloatField(blank=True, null=True)),
                ('classificacao', models.CharField(blank=True, max_length=63, null=True)),
            ],
            options={
                'db_table': 'planeta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('estrela', models.OneToOneField(db_column='estrela', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.estrela')),
                ('nome', models.CharField(blank=True, max_length=31, null=True)),
            ],
            options={
                'db_table': 'sistema',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Nacao',
            fields=[
                ('nome', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('qtd_planetas', models.FloatField(blank=True, null=True)),
                ('federacao', models.ForeignKey(blank=True, db_column='federacao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.federacao')),
            ],
            options={
                'db_table': 'nacao',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('nome', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('inteligente', models.CharField(blank=True, max_length=1, null=True)),
                ('planeta_or', models.ForeignKey(blank=True, db_column='planeta_or', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.planeta')),
            ],
            options={
                'db_table': 'especie',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lider',
            fields=[
                ('cpi', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=15, null=True)),
                ('cargo', models.CharField(max_length=10)),
                ('especie', models.ForeignKey(db_column='especie', on_delete=django.db.models.deletion.DO_NOTHING, to='app.especie')),
                ('nacao', models.ForeignKey(db_column='nacao', on_delete=django.db.models.deletion.DO_NOTHING, to='app.nacao')),
            ],
            options={
                'db_table': 'lider',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Faccao',
            fields=[
                ('nome', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('ideologia', models.CharField(blank=True, max_length=15, null=True)),
                ('qtd_nacoes', models.FloatField(blank=True, null=True)),
                ('lider', models.OneToOneField(db_column='lider', on_delete=django.db.models.deletion.DO_NOTHING, to='app.lider')),
            ],
            options={
                'db_table': 'faccao',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.FloatField(primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=32, null=True)),
                ('id_lider', models.ForeignKey(blank=True, db_column='id_lider', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.lider')),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LogTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users')),
            ],
            options={
                'db_table': 'log_table',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Comunidade',
            fields=[
                ('especie', models.OneToOneField(db_column='especie', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.especie')),
                ('nome', models.CharField(max_length=15, unique=True)),
                ('qtd_habitantes', models.FloatField()),
            ],
            options={
                'db_table': 'comunidade',
                'managed': True,
                'unique_together': {('especie', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Dominancia',
            fields=[
                ('nacao', models.OneToOneField(db_column='nacao', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.nacao')),
                ('data_ini', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('planeta', models.ForeignKey(db_column='planeta', on_delete=django.db.models.deletion.DO_NOTHING, to='app.planeta')),
            ],
            options={
                'db_table': 'dominancia',
                'managed': True,
                'unique_together': {('nacao', 'planeta', 'data_ini')},
            },
        ),
        migrations.CreateModel(
            name='NacaoFaccao',
            fields=[
                ('nacao', models.OneToOneField(db_column='nacao', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.nacao')),
                ('faccao', models.ForeignKey(db_column='faccao', on_delete=django.db.models.deletion.DO_NOTHING, to='app.faccao')),
            ],
            options={
                'db_table': 'nacao_faccao',
                'managed': True,
                'unique_together': {('nacao', 'faccao')},
            },
        ),
        migrations.CreateModel(
            name='OrbitaEstrela',
            fields=[
                ('orbitante', models.OneToOneField(db_column='orbitante', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.estrela')),
                ('dist_min', models.FloatField(blank=True, null=True)),
                ('dist_max', models.FloatField(blank=True, null=True)),
                ('periodo', models.FloatField(blank=True, null=True)),
                ('orbitada', models.ForeignKey(db_column='orbitada', on_delete=django.db.models.deletion.DO_NOTHING, related_name='orbitaestrela_orbitada_set', to='app.estrela')),
            ],
            options={
                'db_table': 'orbita_estrela',
                'managed': True,
                'unique_together': {('orbitante', 'orbitada')},
            },
        ),
        migrations.CreateModel(
            name='Participa',
            fields=[
                ('faccao', models.OneToOneField(db_column='faccao', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.faccao')),
                ('comunidade', models.ForeignKey(db_column='comunidade', on_delete=django.db.models.deletion.DO_NOTHING, related_name='participa_comunidade_set', to='app.comunidade', to_field='nome')),
                ('especie', models.ForeignKey(db_column='especie', on_delete=django.db.models.deletion.DO_NOTHING, to='app.comunidade')),
            ],
            options={
                'db_table': 'participa',
                'managed': True,
                'unique_together': {('faccao', 'especie', 'comunidade')},
            },
        ),
        migrations.CreateModel(
            name='Habitacao',
            fields=[
                ('planeta', models.OneToOneField(db_column='planeta', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.planeta')),
                ('data_ini', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('comunidade', models.ForeignKey(db_column='comunidade', on_delete=django.db.models.deletion.DO_NOTHING, related_name='habitacao_comunidade_set', to='app.comunidade', to_field='nome')),
                ('especie', models.ForeignKey(db_column='especie', on_delete=django.db.models.deletion.DO_NOTHING, to='app.comunidade')),
            ],
            options={
                'db_table': 'habitacao',
                'managed': True,
                'unique_together': {('planeta', 'especie', 'comunidade', 'data_ini')},
            },
        ),
        migrations.CreateModel(
            name='OrbitaPlaneta',
            fields=[
                ('planeta', models.OneToOneField(db_column='planeta', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.planeta')),
                ('dist_min', models.FloatField(blank=True, null=True)),
                ('dist_max', models.FloatField(blank=True, null=True)),
                ('periodo', models.FloatField(blank=True, null=True)),
                ('estrela', models.ForeignKey(db_column='estrela', on_delete=django.db.models.deletion.DO_NOTHING, to='app.estrela')),
            ],
            options={
                'db_table': 'orbita_planeta',
                'managed': True,
                'unique_together': {('planeta', 'estrela')},
            },
        ),
    ]
