# Generated by Django 5.0.6 on 2024-06-30 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('nome', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('inteligente', models.CharField(choices=[('V', 'Verdadeiro'), ('F', 'Falso')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Federacao',
            fields=[
                ('nome', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('data_fund', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Planeta',
            fields=[
                ('id_astro', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('massa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('raio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('classificacao', models.CharField(blank=True, max_length=63, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estrela',
            fields=[
                ('id_estrela', models.CharField(max_length=31, primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=31, null=True)),
                ('classificacao', models.CharField(blank=True, max_length=31, null=True)),
                ('massa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('x', models.DecimalField(decimal_places=2, max_digits=10)),
                ('y', models.DecimalField(decimal_places=2, max_digits=10)),
                ('z', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'unique_together': {('x', 'y', 'z')},
            },
        ),
        migrations.CreateModel(
            name='Lider',
            fields=[
                ('cpi', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=15, null=True)),
                ('cargo', models.CharField(choices=[('COMANDANTE', 'Comandante'), ('OFICIAL', 'Oficial'), ('CIENTISTA', 'Cientista')], max_length=10)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.especie')),
            ],
        ),
        migrations.CreateModel(
            name='Faccao',
            fields=[
                ('nome', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('ideologia', models.CharField(choices=[('PROGRESSISTA', 'Progressista'), ('TOTALITARIA', 'Totalitaria'), ('TRADICIONALISTA', 'Tradicionalista')], max_length=15)),
                ('qtd_nacoes', models.IntegerField()),
                ('lider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.lider')),
            ],
        ),
        migrations.CreateModel(
            name='Nacao',
            fields=[
                ('nome', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('qtd_planetas', models.IntegerField()),
                ('federacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.federacao')),
            ],
        ),
        migrations.AddField(
            model_name='lider',
            name='nacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.nacao'),
        ),
        migrations.AddField(
            model_name='especie',
            name='planeta_or',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.planeta'),
        ),
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=31)),
                ('estrela', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.estrela')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=32)),
                ('id_lider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.lider')),
            ],
        ),
        migrations.CreateModel(
            name='LogTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users')),
            ],
        ),
        migrations.CreateModel(
            name='Comunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=15)),
                ('qtd_habitantes', models.IntegerField()),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.especie')),
            ],
            options={
                'unique_together': {('especie', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='NacaoFaccao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faccao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.faccao')),
                ('nacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.nacao')),
            ],
            options={
                'unique_together': {('nacao', 'faccao')},
            },
        ),
        migrations.CreateModel(
            name='OrbitaEstrela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dist_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dist_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('periodo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orbitada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orbitada', to='app.estrela')),
                ('orbitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orbitante', to='app.estrela')),
            ],
            options={
                'unique_together': {('orbitante', 'orbitada')},
            },
        ),
        migrations.CreateModel(
            name='Participa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comunidade', models.CharField(max_length=15)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.especie')),
                ('faccao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.faccao')),
            ],
            options={
                'unique_together': {('faccao', 'especie', 'comunidade')},
            },
        ),
        migrations.CreateModel(
            name='OrbitaPlaneta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dist_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dist_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('periodo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estrela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estrela')),
                ('planeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.planeta')),
            ],
            options={
                'unique_together': {('planeta', 'estrela')},
            },
        ),
        migrations.CreateModel(
            name='Habitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comunidade', models.CharField(max_length=15)),
                ('data_ini', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.especie')),
                ('planeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.planeta')),
            ],
            options={
                'unique_together': {('planeta', 'especie', 'comunidade', 'data_ini')},
            },
        ),
        migrations.CreateModel(
            name='Dominancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ini', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('nacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.nacao')),
                ('planeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.planeta')),
            ],
            options={
                'unique_together': {('nacao', 'planeta', 'data_ini')},
            },
        ),
    ]
